app:
    resource: "@AppBundle/Controller/"
    type:     annotation

hottes_api:
  path:     /hottes/{_locale}
  defaults: { _controller: AppBundle:Default:all}
  requirements:
      _locale:  en|fr

hottes_distincts:
  path:     /hottes/{_locale}/distinct/{field}
  defaults: { _controller: AppBundle:Default:distinct}
  requirements:
      _locale:  en|fr
